name: Gulp image optimization

on: [push]

jobs:
  gulp-build:

    runs-on: ubuntu-latest

#    steps:
#     - uses: actions/checkout@v2

#     - name: Optimize images using Gulp
#       uses: elstudio/actions-js-build/build@v2

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install

    - run: npm run build --if-present

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: Images optimized.
